// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3zbxDUEpnTNpAfTa5wF46s7cnFVuuWIg',
    appId: '1:247872460292:web:6652d9988e4adcc062c751',
    messagingSenderId: '247872460292',
    projectId: 'bk-work-hours',
    authDomain: 'bk-work-hours.firebaseapp.com',
    storageBucket: 'bk-work-hours.appspot.com',
    measurementId: 'G-ZTDQSCEGRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw-BROZoYqaRDeMv3AYaRqs_smE91pSHg',
    appId: '1:247872460292:android:e3ec2b1d23f76dab62c751',
    messagingSenderId: '247872460292',
    projectId: 'bk-work-hours',
    storageBucket: 'bk-work-hours.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Ke-KSZDGBH1_7OrWkINTnN1V6rNaUyU',
    appId: '1:247872460292:ios:919b49abaaedc8c962c751',
    messagingSenderId: '247872460292',
    projectId: 'bk-work-hours',
    storageBucket: 'bk-work-hours.appspot.com',
    iosClientId: '247872460292-o67e92cmgtkbdgt4rqisle0su2piqa2g.apps.googleusercontent.com',
    iosBundleId: 'com.example.bkWorkHours',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8Ke-KSZDGBH1_7OrWkINTnN1V6rNaUyU',
    appId: '1:247872460292:ios:a922392016ddc85062c751',
    messagingSenderId: '247872460292',
    projectId: 'bk-work-hours',
    storageBucket: 'bk-work-hours.appspot.com',
    iosClientId: '247872460292-7h8amlqqcthb1gbccpurgteslc4ni1jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.bkWorkHours.RunnerTests',
  );
}
